# SonarQube プロジェクト設定ファイル
sonar.projectKey=tohyo-commnication
sonar.projectName=tohyo-commnication

sonar.sources=src

sonar.host.url=http://localhost:9000
sonar.token=sqp_1f79a81d4159c051fe7f3c7b0ea885b215988fbd